package vac.test.data.exceptions

class AuthException(message: String) : RuntimeException(message)